<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Beself\Welcome\Block\Account\Dashboard\Additional $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Additional Information')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <div class="box-content">
                <?php if ($block->getIsB2B()): ?>
                <p>
                    <?= $block->escapeHtml(__('You are included in our B2B program')) ?>
                </p>
                <?php endif; ?>
                <?php if ($block->getProductPreference()): ?>
                    <p>
                        <strong><?= $block->escapeHtml(__('Your favourite type of product is:')) ?></strong> <?= $block->escapeHtml(__($block->getProductPreference()))?>
                    </p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
